# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: linode

provisioner:
  name: salt_solo
  formula: redis
  state_top:
    base:
      "*":
        - redis

platforms:
  - name: debian_jessie

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        redis.sls: pillar_custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - redis
